title: Harmonyc-Khaos
description: SRD for the Harmonyc Khaos Table Top Roleplaying Game
url: "https://harmonyc-khaos.github.io"
baseurl: "/Harmonyc-Khaos"

collections:
  chapters:
    output: false
    sort_by: order

defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: none


kramdown:
  input: GFM
  parse_block_html: true


exclude:
  - README.md
  - SETUP.md